# Training ------------------------------
dynamics:
  name: "dynamics_new"  # remember ln=False during test
  load_name: null  # "dynamics_t_noise_only" # "dynamics_t_2days"  #
  load_type: null  # "latest"  # "best"  #   
  fine_tune: False

  validation_list:    # validation dataset list
    # - "total_t_val"
    # - "total_t_noise_val"
    - "251118_val"
    # - "251229_val"
    # - "251229_try_val"
    # - "online_val"
    - "260317"

  test_list:    # test dataset list
    # - "test"
    # - "251229_total"
    # - "total_t_total"
    # - "251118_val"
    # - "251229_val"
    # - "260225_val"
    # - "total_t_val"
    # - "total_t_noise_val"
    # - "eval"
    # - "train"

  device: cuda
  batch_size: 512
  num_workers: 4
  data_source: "total_new"  # "260121_test"  # "total" # "260104"  #
  bptt_steps: 50
  epochs: 1000
  learning_rate: 0.00001
  weight_decay: 0.0003  # prevent overfitting
  max_grad_norm: 2     # 0 means no gradient clipping
  discount: 1.0        # loss discount factor through time, prevent gradient exploding
  loss_weight:         # 50_step res, abs, 150_step res, abs
    k_output_smooth: 0.0           # smooth loss weight to the outputs
    k_hidden_smooth: 0.0           # smooth loss weight to the hidden states
    k_rotvec: 12 # 180 # 65       # orientation loss weight 600 240 500
    k_pos: 0.0015 # 0.003  # 0.007  # 0.0005      # position loss weight 0.12 0.17 0.19
    k_l: 0.8  #  0.78  # 0.011          # length loss weight 1.65 0.70 2.00
    k_v: 0.08 # 0.025  # 0.15  # 0.46          # velocity loss weight 1.70 10.5 2.20
    k_torque: 50  # 90 # 100  # 440 # 70      # torque loss weight 180 190 120


policy: 
  name: "policy_new_mlp_ignore_h"  # "policy_new_hidden_dynamics"  # "policy_260121_test_pose_only"  # "policy_stochastic_big_smooth"  # "policy_rnn_tf"
  dynamics_name: "dynamics_new"  # "dynamics_t_"  # null  #"dynamics_gru"     # path to the load dynamics model checkpoint
  dynamics_load_type: "latest"  # null  # "best"  # "latest"
  load_name: "policy_new_mlp_ignore_h"  # "policy_new_hidden_dynamics" # null  # "policy_t_obs_ref_450_6" # "policy_t_"  # 
  policy_load_type: "latest"  # null  #"best"
  fine_tune: False

  obs_ref: False  # whether use real future obs as reference during training (including eval and test)

  validation_list:    # validation dataset list
    # - "251118_val"`
    # - "260225_val"
    # - "251229_val"
    # - "251229_try_val"

  test_list:    # test dataset list
    - "260317"
    # - "260408_mlp_ignore_h"

  device: cuda
  batch_size: 256
  num_workers: 4
  data_source: "total_new"  # "260317_policy_test_compare"  # "mpc"  # 
  min_regressive_steps: 50  # loading traj length must be longer than this value

  # for dataset ref
  closer_scale: 0.0            # 0: original ref, 1: shift to the same initial pose
                                # sample between (closer_scale, 1) to scale the delta refw
                                # 0.0 means using original ref trajectory
  # for obs ref
  sine_freq_max: 0.005   # 0.005*50=0.25hz, set a maximum frequency of the sine wave noise
  step_rate: 0.001       # the probability of adding a step noise at each time step
  bias_max_pos: 20  # 8         # mm, set a maximum distance from the initial
  sine_amp_max_pos: 25  # 8      # mm, set a maximum amplitude of the sine wave noise
  step_max_pos: 20  # 8          # mm, set a maximum distance of the step noise
  bias_max_rot: 0.1  # 0.03        # rad, set a maximum distance from the initial
  sine_amp_max_rot: 0.1  # 0.03     # rad, set a maximum amplitude of the sine wave noise
  step_max_rot: 0.1  # 0.03        # rad, set a maximum distance of the step noise

  bptt_steps: 250
  truncation_steps: 250         # for truncated bptt
  epochs: 1000
  learning_rate: 0.00001        # 0.00005
  weight_decay: 0.0003
  max_grad_norm: 2              # 0 means no gradient clipping
  discount: 1.0                # loss discount factor through time, prevent gradient exploding
  loss_weight:
    k_smooth: 10  # 10          # smooth loss weight
    k_rotvec: 40  # 40          # orientation loss weight
    k_pos: 0.001 # 0.001        # position loss weight
    k_imitation: 0.00001        # control output near to the dataset control


mpc:
  name: "mpc_512_iter_20_smooth"
  dynamics_name: "dynamics_new"
  dynamics_load_type: "latest"
  device: cuda
  data_source: "mpc"
  test_list:    # test dataset(trajectories) list
    - "2.0_R"
    - "2.0_O"
    - "2.0_B"
    - "2.0_T"
    - "2.0_straight_line"
    - "3.0_R"
    - "3.0_O"
    - "3.0_B"
    - "3.0_T"
    - "3.0_straight_line"
    - "5.0_R"
    - "5.0_O"
    - "5.0_B"
    - "5.0_T"
    - "5.0_straight_line"

  obs_ref: False  # whether use real future obs as reference during training (including eval and test)

  # for dataset ref
  closer_scale: 0            # 0: original ref, 1: shift to the same initial pose
                                # sample between (closer_scale, 1) to scale the delta refw
                                # 0.0 means using original ref trajectory
  # for obs ref
  sine_freq_max: 0.005   # 0.005*50=0.25hz, set a maximum frequency of the sine wave noise
  step_rate: 0.001       # the probability of adding a step noise at each time step
  bias_max_pos: 20          # mm, set a maximum distance from the initial
  sine_amp_max_pos: 25      # mm, set a maximum amplitude of the sine wave noise
  step_max_pos: 20          # mm, set a maximum distance of the step noise
  bias_max_rot: 0.1         # rad, set a maximum distance from the initial
  sine_amp_max_rot: 0.1     # rad, set a maximum amplitude of the sine wave noise
  step_max_rot: 0.1         # rad, set a maximum distance of the step noise

  batch_size: 1
  num_workers: 0
  min_regressive_steps: 50  # loading traj length must be longer than this value
  freq_downsample: 1        # downsample frequency of the control sequence for training

  bptt_steps: 2800
  truncation_steps: 2800      # for truncated bptt
  learning_rate: 1.0
  max_grad_norm: 2.0
  optimize_iters: 512
  discount: 1.0
  u_clip: 12.56637
  loss_weight:
    k_smooth: 20
    k_rotvec: 40  # 0.00001
    k_pos: 0.001


online:
  name: "online_260112"
  epochs: 500
  test_traj_num: 5
  rollouts_per_epoch: 3
  round_time_per_epoch: 5
  test_after_epoch: 5
  socket_port: 12345
  skip_initial_test: True
  update_dynamics: True